#!/bin/bash
# Credits: @mrismanaziz
# Copyright (C) 2022 Pyro-ManUserbot
#
# This file is a part of < https://github.com/mrismanaziz/PyroMan-Userbot/ >
# PLease read the GNU Affero General Public License in
# <https://www.github.com/mrismanaziz/PyroMan-Userbot/blob/main/LICENSE/>.
#
# t.me/SharingUserbot & t.me/Lunatic0de

_starter () {
    echo "Downloading source code"
    git clone https://github.com/hdiiofficial/PiPyro-Userbot
    cd PiPyro-Userbot/ && rm -rf .git
    python3 ../updater.py ../requirements.txt requirements.txt
    echo "PiPyro-Userbot v0.1.0, Copyright © 2022 (Hadi) <https://github.com/hdiiofficial>"
    python3 userbot.py
}

_starter
